name: Mirror to Codeberg

on:
  push:
    branches:
      - '**'
  workflow_dispatch:

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Fetch all branches and tags
        run: |
          git fetch --all --prune
      - name: Mirror to Codeberg
        env:
          MIRROR_URL: ${{ secrets.CODEBERG_MIRROR_URL }}
        run: |
          git remote add codeberg "$MIRROR_URL"
          git push --mirror codeberg