name: Mirror to Codeberg

on:
  push:
    branches:
      - '**'
  workflow_dispatch:

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Bare clone the repository
        run: |
          git clone --mirror https://github.com/${{ github.repository }} repo.git
          cd repo.git
          git remote add codeberg ${{ secrets.CODEBERG_MIRROR_URL }}
          git push --mirror codeberg
